// resources/js/views/UserForm.jsx
import { useEffect, useState } from "react"
import { useNavigate, useParams } from "react-router-dom"
import axiosClient from "../axios-client"
import { useStateContext } from "../Contexts/ContextProvider"


export default function UserForm() {
    const {id} = useParams()
    const navigate = useNavigate()
    const {setNotification} = useStateContext()
    const [errors, setErrors] = useState('')
    const [loading, setLoading] = useState(false)
    const [user, setUser] = useState({
        id: null,
        name: '',
        email: '',
        password: '',
        password_confirmation: ''
    })

    if(id) {
        useEffect(() => {
            setLoading(true)
            axiosClient.get(`/api/users/${id}`).then(({data}) => {
                setLoading(false)
                setUser(data.data)
            }).catch(() => {
                setLoading(false)
            })
        }, [])
    }

    const onSubmit = (e) => {
        e.preventDefault()
        if(user.id) {
            axiosClient.put(`/api/users/${user.id}`, user)
                .then(() => {
                    setNotification('user was successfully updated')
                    navigate('/react/users')
                }).catch((error) => {
                    const response = error.response
                    if(response && response.status === 422) {
                        setErrors(response.data.errors)
                    }
                })
        } else {
            axiosClient.post(`/api/users`, user)
                .then(() => {
                    setNotification('user was successfully created')
                    navigate('/react/users')
                }).catch((error) => {
                    const response = error.response
                    if(response && response.status === 422) {
                        setErrors(response.data.errors)
                    }
                })
        }
    }

    return (
        <>
            { !user.id && <h1>New User</h1> }
            { user.id && <h1>Update User: {user.name} </h1> }
            
            <div className="card animated fadeInDown">
                { loading && (
                    <div className="text-center">Loading ...</div>
                ) }

                { !loading && 
                    <form onSubmit={onSubmit}>
                        <input value={user.name} type="text" onChange={e => setUser({...user, name: e.target.value})} placeholder="Fullname" />
                        {errors.name && <div className="text-danger">{errors.name}</div>}
                        
                        <input value={user.email} type="text" onChange={e => setUser({...user, email: e.target.value})} placeholder="Email" />
                        {errors.email && <div className="text-danger">{errors.email}</div>}

                        <input type="text" onChange={e => setUser({...user, password: e.target.value})} placeholder="Password" />
                        {errors.password && <div className="text-danger">{errors.password}</div>}

                        <input type="text" onChange={e => setUser({...user, password_confirmation: e.target.value})} placeholder="Password Confirmation" />
                        <button type="submit" className="btn">Save</button>
                    </form>
                }
            </div>
        </>
    )
}

// resources/js/pages/UserForm.vue
<template>
    <div>
        <h1 v-if="!user.id">New User</h1>
        <h1 v-if="user.id">Update User: {{ user.name }}</h1>
            
        <div className="card animated fadeInDown">
            <form @submit="handleSubmit">
                <input type="text" v-model="user.name" placeholder="Fullname" />
                <div v-if="errors.name" style="color: red">
                    {{ errors.name[0] }}
                </div>

                <input type="text" v-model="user.email" placeholder="Email" />
                <div v-if="errors.email" style="color: red">
                    {{ errors.email[0] }}
                </div>

                <input type="text" placeholder="Password" v-model="user.password" />
                <div v-if="errors.password" style="color: red">
                    {{ errors.password[0] }}
                </div>

                <input type="text" placeholder="Password Confirmation" v-model="user.password_confirmation" />
                <button type="submit" className="btn">Save</button>
            </form>
        </div>
    </div>
</template>

<script>
	export default {
		data() {
			return {
				user: {
                    id: '',
                    name: '',
                    email: '',
                    password: '',
                    password_confirmation: ''
                },
                errors: {}
			}
		},
		methods: {
			async fetchUser(id) {
                const responseUser = await axios.get(`/api/users/${id}`, {
                    headers: {
                        'Content-Type': 'application/json',
                        'Authorization': `Bearer ${localStorage.getItem('ACCESS_TOKEN')}`
                    }
                })
                
                this.user = responseUser.data.data
			},
            handleSubmit(e) {
                e.preventDefault()
                if(this.user.id) {
                    axios.put(`/api/users/${this.user.id}`, this.user, {
                            headers: {
                                'Content-Type': 'application/json',
                                'Authorization': `Bearer ${localStorage.getItem('ACCESS_TOKEN')}`
                            }
                        })
                        .then(() => {
                            this.$router.push({name: 'Users'})
                        }).catch((error) => {
                            const response = error.response
                            if(response && response.status === 422) {
                                this.errors = response.data.errors
                            }
                        })
                } else {
                    axios.post(`/api/users`, this.user, {
                            headers: {
                                'Content-Type': 'application/json',
                                'Authorization': `Bearer ${localStorage.getItem('ACCESS_TOKEN')}`
                            }
                        })
                        .then(() => {
                            this.$router.push({name: 'Users'})
                        }).catch((error) => {
                            const response = error.response
                            if(response && response.status === 422) {
                                this.errors = response.data.errors
                            }
                        })
                }
            }
		},
		async mounted() {
            if(this.$route.params.id) {
                const id = this.$route.params.id
			    await this.fetchUser(id)
            }
		}
	}
</script>
